[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
ClientMonitor = 15000
Host = 'device-simple'
Port = 49990
Protocol = 'http'
StartupMsg = 'device simple started'
Timeout = 5000
ConnectRetries = 20
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'edgex-core-data'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'edgex-core-metadata'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'edgex-support-logging'
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false

[Logging]
EnableRemote = false
File = '/edgex/logs/device-simple.log'

# Pre-define Devices
[[DeviceList]]
  Name = 'Simple-Device01'
  Profile = 'Simple-Device'
  Description = 'Example of Simple Device'
  Labels = [ 'industrial' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = 'simple01'
      Port = '300'
  [[DeviceList.AutoEvents]]
    Frequency = '10s'
    OnChange = false
    Resource = 'Switch'
  [[DeviceList.AutoEvents]]
    Frequency = '30s'
    OnChange = false
    Resource = 'Image'
